### PR TITLE
Introducing Replicated Logs

### PR DESCRIPTION
**Pull request by goedderz**
Companion PR of https://github.com/arangodb/arangodb/pull/14486.

This PR _must not_ be merged before #14486, but can safely be merged later. It enables tests that are only necessary for things introduced by #14486.

### CODE REVIEW

**Comment by goedderz** [comment]
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/16555/

**Review by mchacki — APPROVED** [review]
It looks good to me however someone with more Oskar experience should take a better look at this.

**Comment by jsteemann** [comment]
Note the future reviewers: the test suite `replication2_client` is already blocklisted in 3.6, 3.7 and 3.8.

**Review by jsteemann — APPROVED** [review]
LGTM

**Comment by goedderz** [comment]
https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/16570/

**Pull request merged**
