### PR TITLE
also kill stray ssh-agents

### PR DESCRIPTION
**Pull request by dothebart**
kill stray ssh-agents as well.

### CODE REVIEW

**Comment by dothebart** [comment]
https://jenkins01.arangodb.biz/job/arangodb-matrix-pr-mac-onlycatch.x86-64/19866/

**Comment by dothebart** [comment]
https://jenkins01.arangodb.biz/job/arangodb-matrix-pr-mac-onlycatch.x86-64/19871/EDITION=community,limit=mac&&test&&x86-64/console
demonstrates the function.

**Review by fceller — APPROVED** [review]
LGTM

**Comment by dothebart** [comment]
already merged as part of https://github.com/arangodb/oskar/pull/427/files

**Pull request closed without merging**
