### PR TITLE
disable conditional log string generation for asan and code coverage.

### PR DESCRIPTION
**Pull request by dothebart**
for https://github.com/arangodb/arangodb/pull/13019

### CODE REVIEW

**Comment by dothebart** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-ANY-linux-asan/452/

**Comment by dothebart** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-ANY-linux-asan/453/

**Comment by dothebart** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-ANY-linux-asan/454/

**Comment by dothebart** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-ANY-linux-asan/456/

**Comment by dothebart** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-ANY-linux-asan/457/

**Comment by dothebart** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-ANY-linux-asan/458/

**Review by fceller — APPROVED** [review]
LGTM

**Pull request merged**
