### PR TITLE
Enable llvm symbolizer

### PR DESCRIPTION
**Pull request by MBkkt**
We reduced size of output, so I think we can revert addr2line work-around and have line number in tsan stacktrace

Should be tested before merge! (suppressions don't work with llvm-symbolizer before ApplicationServerT changes)

Should be tested only after this PR: https://github.com/arangodb/arangodb/pull/17786

### CODE REVIEW

**Comment by MBkkt** [comment]
https://jenkins.arangodb.biz/job/arangodb-ANY-linux-san.x86-64/1463/

**Comment by MBkkt** [comment]
https://jenkins.arangodb.biz/job/arangodb-ANY-linux-san.x86-64/1464/

**Review by dothebart — APPROVED** [review]

**Comment by KVS85** [comment]
- [ ] 3.10: https://jenkins.arangodb.biz/job/arangodb-ANY-linux-san.x86-64/1468/
- [ ] 3.9: https://jenkins.arangodb.biz/job/arangodb-ANY-linux-san.x86-64/1469/
- [ ] 3.8: https://jenkins.arangodb.biz/job/arangodb-ANY-linux-san.x86-64/1470/

**Review by KVS85 — APPROVED** [review]

**Review by KVS85 — APPROVED** [review]

**Comment by KVS85** [comment]
- [ ] devel: https://jenkins.arangodb.biz/job/arangodb-ANY-linux-san.x86-64/1554/
- [ ] 3.10: https://jenkins.arangodb.biz/job/arangodb-ANY-linux-san.x86-64/1555/
- [ ] 3.9: https://jenkins.arangodb.biz/job/arangodb-ANY-linux-san.x86-64/1556/
- [ ] 3.8: https://jenkins.arangodb.biz/job/arangodb-ANY-linux-san.x86-64/1557/

**Comment by KVS85** [comment]
- [ ] 3.10: https://jenkins.arangodb.biz/job/arangodb-ANY-linux-san.x86-64/1560/

**Pull request merged**
