### PR TITLE
also run shell tests with http2

### PR DESCRIPTION
**Pull request by dothebart**

### CODE REVIEW

**Comment by dothebart** [comment]
http://jenkins01.arangodb.biz:8080/view/PR/job/arangodb-matrix-pr/8556/ - expecting `shell-document.js:testDBExistsDocument()` to fail.

**Comment by dothebart** [comment]
Windows devel enterprise diverted already, re-running: 
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr-windows/2528/

**Comment by dothebart** [comment]
http2 part on windows successfully verified the currently existing error.

**Comment by graetzer** [comment]
http://jenkins01.arangodb.biz:8080/job/arangodb-matrix-pr-linux/10336/

**Comment by dothebart** [comment]
ready to merge.

**Pull request merged**
