### PR TITLE
[QA-191] Speed-up CI jobs execution on Windows in Jenkins

### PR DESCRIPTION
**Pull request by KVS85**
Modify oskar part for Windows to speedup CI execution according to Ideas on how to Speed up Jenkins PR runs. The following parts should be covered:
- Only Zip windows binaries if the test failed to have something for debugger
  - ZIP packages will be produced only for packaging jobs where we can deliver externally (without additional deps to 7Zip)
- Create 7z packages instead of zip on Windows
- Store only `arango*` PDBs in both PDB archive and crash reports

Additionally, some parts were adjusted to macOS/Linux version of oskar.

### CODE REVIEW

**Comment by KVS85** [comment]
PRs:
- [ ] devel: http://jenkins01.arangodb.biz:8080/view/Windows/job/arangodb-matrix-pr-windows/11831/
- [ ] 3.9: http://jenkins01.arangodb.biz:8080/view/Windows/job/arangodb-matrix-pr-windows/11832/
- [ ] 3.8: http://jenkins01.arangodb.biz:8080/view/Windows/job/arangodb-matrix-pr-windows/11833/
- [ ] 3.7: http://jenkins01.arangodb.biz:8080/view/Windows/job/arangodb-matrix-pr-windows/11834/

Matrix:
- [ ] devel: http://jenkins01.arangodb.biz:8080/view/Windows/job/arangodb-ANY-windows-matrix/2899/
- [ ] 3.9: http://jenkins01.arangodb.biz:8080/view/Windows/job/arangodb-ANY-windows-matrix/2900/
- [ ] 3.8: http://jenkins01.arangodb.biz:8080/view/Windows/job/arangodb-ANY-windows-matrix/2901/
- [ ] 3.7: http://jenkins01.arangodb.biz:8080/view/Windows/job/arangodb-ANY-windows-matrix/2902/

Packages:
- [ ] devel: http://jenkins01.arangodb.biz:8080/view/Windows/job/arangodb-ANY-windows-packages/2336/
- [ ] 3.9: http://jenkins01.arangodb.biz:8080/view/Windows/job/arangodb-ANY-windows-packages/2337/
- [ ] 3.8: http://jenkins01.arangodb.biz:8080/view/Windows/job/arangodb-ANY-windows-packages/2338/
- [ ] 3.7: http://jenkins01.arangodb.biz:8080/view/Windows/job/arangodb-ANY-windows-packages/2339/

**Review by fceller — APPROVED** [review]

**Review by dothebart — APPROVED** [review]

**Comment by KVS85** [comment]
PRs:
- [ ] devel: http://jenkins01.arangodb.biz:8080/view/Windows/job/arangodb-matrix-pr-windows/11831/
- [ ] 3.9: http://jenkins01.arangodb.biz:8080/view/Windows/job/arangodb-matrix-pr-windows/11832/
- [ ] 3.8: http://jenkins01.arangodb.biz:8080/view/Windows/job/arangodb-matrix-pr-windows/11833/
- [ ] 3.7: http://jenkins01.arangodb.biz:8080/view/Windows/job/arangodb-matrix-pr-windows/11834/

Matrix:
- [ ] devel: http://jenkins01.arangodb.biz:8080/view/Windows/job/arangodb-ANY-windows-matrix/2907/
- [ ] 3.9: http://jenkins01.arangodb.biz:8080/view/Windows/job/arangodb-ANY-windows-matrix/2908/
- [ ] 3.8: http://jenkins01.arangodb.biz:8080/view/Windows/job/arangodb-ANY-windows-matrix/2909/
- [ ] 3.7: http://jenkins01.arangodb.biz:8080/view/Windows/job/arangodb-ANY-windows-matrix/2910/

Packages:
- [ ] devel: http://jenkins01.arangodb.biz:8080/view/Windows/job/arangodb-ANY-windows-packages/2336/
- [ ] 3.9: http://jenkins01.arangodb.biz:8080/view/Windows/job/arangodb-ANY-windows-packages/2337/
- [ ] 3.8: http://jenkins01.arangodb.biz:8080/view/Windows/job/arangodb-ANY-windows-packages/2338/
- [ ] 3.7: http://jenkins01.arangodb.biz:8080/view/Windows/job/arangodb-ANY-windows-packages/2339/

**Comment by KVS85** [comment]
Matrix:
- [ ] devel: https://jenkins.arangodb.biz/job/arangodb-ANY-windows-matrix/2964/
- [ ] 3.9: https://jenkins.arangodb.biz/job/arangodb-ANY-windows-matrix/2965/
- [ ] 3.8: https://jenkins.arangodb.biz/job/arangodb-ANY-windows-matrix/2966/
- [ ] 3.7: https://jenkins.arangodb.biz/job/arangodb-ANY-windows-matrix/2967/

Packages:
- [ ] devel: 
- [ ] 3.9: 
- [ ] 3.8: 
- [ ] 3.7:

**Comment by KVS85** [comment]
Matrix:
- [ ] devel: https://jenkins.arangodb.biz/job/arangodb-ANY-windows-matrix/2982/
- [ ] 3.9: https://jenkins.arangodb.biz/job/arangodb-ANY-windows-matrix/2983/
- [ ] 3.8: https://jenkins.arangodb.biz/job/arangodb-ANY-windows-matrix/2984/
- [ ] 3.7: https://jenkins.arangodb.biz/job/arangodb-ANY-windows-matrix/2985/

Packages:
- [ ] devel: https://jenkins.arangodb.biz/view/Windows/job/arangodb-ANY-windows-packages/2411/
- [ ] 3.9: https://jenkins.arangodb.biz/view/Windows/job/arangodb-ANY-windows-packages/2412/
- [ ] 3.8: https://jenkins.arangodb.biz/view/Windows/job/arangodb-ANY-windows-packages/2413/
- [ ] 3.7: https://jenkins.arangodb.biz/view/Windows/job/arangodb-ANY-windows-packages/2414/

PRs:
- [ ] devel: https://jenkins.arangodb.biz/job/arangodb-matrix-pr-windows/11979/
- [ ] 3.9: https://jenkins.arangodb.biz/job/arangodb-matrix-pr-windows/11980/
- [ ] 3.8: https://jenkins.arangodb.biz/job/arangodb-matrix-pr-windows/11981/
- [ ] 3.7: https://jenkins.arangodb.biz/job/arangodb-matrix-pr-windows/11982/

**Comment by KVS85** [comment]
Matrix:
- [ ] devel: https://jenkins.arangodb.biz/job/arangodb-ANY-windows-matrix/2986/
- [ ] 3.9: https://jenkins.arangodb.biz/job/arangodb-ANY-windows-matrix/2987/
- [ ] 3.8: https://jenkins.arangodb.biz/job/arangodb-ANY-windows-matrix/2988/
- [ ] 3.7: https://jenkins.arangodb.biz/job/arangodb-ANY-windows-matrix/2989/

Packages:
- [ ] devel: https://jenkins.arangodb.biz/view/Windows/job/arangodb-ANY-windows-packages/2411/
- [ ] 3.9: https://jenkins.arangodb.biz/view/Windows/job/arangodb-ANY-windows-packages/2412/
- [ ] 3.8: https://jenkins.arangodb.biz/view/Windows/job/arangodb-ANY-windows-packages/2413/
- [ ] 3.7: https://jenkins.arangodb.biz/view/Windows/job/arangodb-ANY-windows-packages/2414/

PRs:
- [ ] devel: https://jenkins.arangodb.biz/job/arangodb-matrix-pr-windows/11979/
- [ ] 3.9: https://jenkins.arangodb.biz/job/arangodb-matrix-pr-windows/11980/
- [ ] 3.8: https://jenkins.arangodb.biz/job/arangodb-matrix-pr-windows/11981/
- [ ] 3.7: https://jenkins.arangodb.biz/job/arangodb-matrix-pr-windows/11982/

**Comment by KVS85** [comment]
Matrix:
- [ ] devel: https://jenkins.arangodb.biz/job/arangodb-ANY-windows-matrix/2992/
- [ ] 3.9: https://jenkins.arangodb.biz/job/arangodb-ANY-windows-matrix/2993/
- [ ] 3.8: https://jenkins.arangodb.biz/job/arangodb-ANY-windows-matrix/2994/
- [ ] 3.7: https://jenkins.arangodb.biz/job/arangodb-ANY-windows-matrix/2995/

Packages:
- [ ] devel: https://jenkins.arangodb.biz/view/Windows/job/arangodb-ANY-windows-packages/2420/
- [ ] 3.9: https://jenkins.arangodb.biz/view/Windows/job/arangodb-ANY-windows-packages/2421/
- [ ] 3.8: https://jenkins.arangodb.biz/view/Windows/job/arangodb-ANY-windows-packages/2422/
- [ ] 3.7: https://jenkins.arangodb.biz/view/Windows/job/arangodb-ANY-windows-packages/2423/

PRs:
- [ ] devel: https://jenkins.arangodb.biz/job/arangodb-matrix-pr-windows/11997/
- [ ] 3.9: https://jenkins.arangodb.biz/job/arangodb-matrix-pr-windows/11998/
- [ ] 3.8: https://jenkins.arangodb.biz/job/arangodb-matrix-pr-windows/11999/
- [ ] 3.7: https://jenkins.arangodb.biz/job/arangodb-matrix-pr-windows/12000/

**Comment by KVS85** [comment]
Matrix:
- [ ] devel: https://jenkins.arangodb.biz/job/arangodb-ANY-windows-matrix/2997/
- [ ] 3.9: https://jenkins.arangodb.biz/job/arangodb-ANY-windows-matrix/2998/
- [ ] 3.8: https://jenkins.arangodb.biz/job/arangodb-ANY-windows-matrix/2999/
- [ ] 3.7: https://jenkins.arangodb.biz/job/arangodb-ANY-windows-matrix/3000/

Packages:
- [ ] devel: https://jenkins.arangodb.biz/view/Windows/job/arangodb-ANY-windows-packages/2426/
- [ ] 3.9: https://jenkins.arangodb.biz/view/Windows/job/arangodb-ANY-windows-packages/2427/
- [ ] 3.8: https://jenkins.arangodb.biz/view/Windows/job/arangodb-ANY-windows-packages/2428/
- [ ] 3.7: https://jenkins.arangodb.biz/view/Windows/job/arangodb-ANY-windows-packages/2429/

PRs:
- [ ] devel: https://jenkins.arangodb.biz/job/arangodb-matrix-pr-windows/12005/
- [ ] 3.9: https://jenkins.arangodb.biz/job/arangodb-matrix-pr-windows/12006/
- [ ] 3.8: https://jenkins.arangodb.biz/job/arangodb-matrix-pr-windows/12007/
- [ ] 3.7: https://jenkins.arangodb.biz/job/arangodb-matrix-pr-windows/12008/

**Comment by KVS85** [comment]
Matrix:
- [ ] devel: https://jenkins.arangodb.biz/job/arangodb-ANY-windows-matrix/3001/
- [ ] 3.9: https://jenkins.arangodb.biz/job/arangodb-ANY-windows-matrix/3002/
- [ ] 3.8: https://jenkins.arangodb.biz/job/arangodb-ANY-windows-matrix/3003/
- [ ] 3.7: https://jenkins.arangodb.biz/job/arangodb-ANY-windows-matrix/3004/

Packages:
- [ ] devel: https://jenkins.arangodb.biz/view/Windows/job/arangodb-ANY-windows-packages/2430/
- [ ] 3.9: https://jenkins.arangodb.biz/view/Windows/job/arangodb-ANY-windows-packages/2431/
- [ ] 3.8: https://jenkins.arangodb.biz/view/Windows/job/arangodb-ANY-windows-packages/2432/
- [ ] 3.7: https://jenkins.arangodb.biz/view/Windows/job/arangodb-ANY-windows-packages/2433/

PRs:
- [ ] devel: https://jenkins.arangodb.biz/job/arangodb-matrix-pr-windows/12015/
- [ ] 3.9: https://jenkins.arangodb.biz/job/arangodb-matrix-pr-windows/12016/
- [ ] 3.8: https://jenkins.arangodb.biz/job/arangodb-matrix-pr-windows/12017/
- [ ] 3.7: https://jenkins.arangodb.biz/job/arangodb-matrix-pr-windows/12018/

**Pull request merged**
