### PR TITLE
Start/stop a local LDAP docker server

### PR DESCRIPTION
**Pull request by mchacki**
Added convenience functions to start/stop ldap server locally (requires docker)

This is now used in fullNightlyTestSuite.

Jenkins branch supposed to test this:
http://jenkins01.arangodb.biz:8080/view/Nightlies/job/arangodb-3.4-linux-matrix-nightly/76/

### CODE REVIEW

**Comment by mchacki** [comment]
@Luschgy was totally right, thanks for spotting should all be fixed now!

**Comment by mchacki** [comment]
Next jenkins:
http://jenkins01.arangodb.biz:8080/view/Nightlies/job/arangodb-3.4-linux-matrix-nightly/78/

**Comment by mchacki** [comment]
Ok, so the jenkins run is red,
But all of this is unrelated to this PR.
We have executed LDAP tests sucessfully with it.

**Comment by fceller** [comment]
@Luschgy have your concerns been addressed now?

**Comment by Luschgy** [comment]
A Networkname was added so i'm happy now

**Pull request merged**
