### PR TITLE
Feature/clean docker containers

### PR DESCRIPTION
**Pull request by dothebart**
output on my machine:
```
deleting <Image: 'arangodb/arangosync:latest'> None
deleting <Image: 'arangodb/release-test-automation-tar:1.2'> None
deleting <Image: 'arangodb/release-test-automation-deb:1.2'> None
deleting <Image: 'arangodb/release-test-automation-tar:1.1'> None
deleting <Image: 'release-test-automation-tar:1.1'> None
deleting <Image: 'ldaptest:latest'> None
deleting <Image: 'arangodb/release-test-automation-tar:1.0'> None
deleting <Image: 'arangodb/release-test-automation-deb-1.0:1.0'> None
deleting <Image: 'quay.io/minio/minio:latest'> None
deleting <Image: 'arangodb/release-test-automation-deb:1.0'> None
deleting <Image: 'arangodb/release-test-automation-rpm:1.0'> None
deleting <Image: 'golang:1.16.6-alpine3.14'> None
deleting <Image: 'arangodb/enterprise:3.7.12'> None
deleting <Image: 'arangosync-builder:latest'> None
deleting <Image: 'localtesting/arangosync-tests:dev'> None
deleting <Image: 'localtesting/arangosync:latest'> None
deleting <Image: 'arangodb/ldap-test:latest'> None
deleting <Image: 'blarg:latest'> None
deleting <Image: 'fedora:latest'> None
deleting <Image: 'alpine:3.13'> None
deleting <Image: 'arangodb/enterprise-preview:3.7.10'> None
deleting <Image: 'golang:1.16.0-alpine3.13'> None
deleting <Image: 'arangodb/release-test-automation:latest'> None
deleting <Image: 'docker_tar:latest'> None
deleting <Image: 'c7-systemd:latest'> None
deleting <Image: 'test_tar:latest'> None
deleting <Image: 'arangodb/enterprise-test:3.7-removehdr'> None
```

### CODE REVIEW

**Comment by fceller** [comment]
Please add oskar function "imageNames" to output images, like UBUNTUBUILDIMAGE3_NAME

You can even add other images there like "debian", ...

**Comment by KVS85** [comment]
https://jenkins01.arangodb.biz/job/arangodb-matrix-pr-linux.x86-64/25802/

**Comment by KVS85** [comment]
https://jenkins01.arangodb.biz/job/arangodb-matrix-pr-linux.x86-64/25803/

**Review by fceller — APPROVED** [review]

**Comment by dothebart** [comment]
https://jenkins01.arangodb.biz/view/PR/job/arangodb-matrix-pr/25785/ run with actively sweeping containers and images

**Pull request merged**
