### PR TITLE
convert to classes, use click

### PR DESCRIPTION
**Pull request by dothebart**

### CODE REVIEW

**Comment by dothebart** [comment]
on hold till the click module is deployed to the CI machines.

**Comment by KVS85** [comment]
http://jenkins.arangodb.biz:8080/job/helper-performance-import/1383

**Comment by KVS85** [comment]
Tests blue.

**Review by KVS85 — APPROVED** [review]
LGTM.

**Comment by KVS85** [comment]
http://jenkins.arangodb.biz:8080/job/helper-performance-import/1384/

**Comment by KVS85** [comment]
Tests blue.

**Review by fceller — APPROVED** [review]

**Pull request merged**
