### PR TITLE
Fixed detection of wrong pull request

### PR DESCRIPTION
**Pull request by hkernbach**
This PR fixes the sometimes not working detection of a pull request. 

Example: In case we do not have created a PR and run a PR-test based on `devel/devel` we do not have an existing PR created on GitHub. But there might be forks of `devel/devel` which might be detected which are not even part of our repository. This PR fixes this issue. 

Also it optimizes the way we choose relevant found pull request items. Old variant just choose the latest item without further validation. Now we will iterate through all of the found items in reverse order (latest to oldest) and only pick an owned arangodb pr in case we've found one.

### CODE REVIEW

**Comment by hkernbach** [comment]
Should NOT detect any PR:
- https://jenkins.arangodb.biz:3456/view/PR/job/arangodb-matrix-pr/22657/

Should detect PR: 
- https://jenkins.arangodb.biz:3456/view/PR/job/arangodb-matrix-pr/22658/

**Review by mpoeter — CHANGES_REQUESTED** [review]
We should use a search request that explicitly specifies the repo. E.g. `https://api.github.com/search/issues?q=ff732548654c349a0379808a5384407b793fde07%20repo:arangodb/arangodb`

**Comment by hkernbach** [comment]
@mpoeter added your suggestion:
```
const checkPRExists = (sha) => {
  const queryString = encodeURIComponent(`${sha} repo:${repository}`);
  const checkPRExistencePath = `/search/issues?q=${queryString}`;
  getRequest(checkPRExistencePath, checkPRMethod, sha);
}
```

**Review by mpoeter — APPROVED** [review]

**Review by KVS85 — APPROVED** [review]
LGTM.

**Comment by KVS85** [comment]
- [ ] https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/23404/

- [ ] https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/23405/

**Pull request merged**
