### PR TITLE
Add allProtocols flag that runs a test suite for http+http2+vst

### PR DESCRIPTION
**Pull request by mpoeter**

### CODE REVIEW

**Comment by mpoeter** [comment]
https://jenkins.arangodb.biz/job/arangodb-matrix-pr/28422/

**Comment by dothebart** [comment]
Great. Whats missing now would be a way to skip this multiplexing for mac, since we need to cut down on the tests executed.

**Comment by KVS85** [comment]
- [ ] https://jenkins.arangodb.biz/job/arangodb-matrix-pr/32934/

**Comment by KVS85** [comment]
- [ ] https://jenkins.arangodb.biz/job/arangodb-matrix-pr/32935/

**Comment by dothebart** [comment]
decided to go via test-definitions.txt with mostly readily existing testing.js extensions.

**Pull request closed without merging**
