### PR TITLE
Bug fix/improve error message

### PR DESCRIPTION
**Pull request by dothebart**
make it more precise which sate of initial cleanup we're in

### CODE REVIEW

**Comment by KVS85** [comment]
- [ ] https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/27578/

**Comment by KVS85** [comment]
- [ ] https://jenkins.arangodb.biz/view/PR/job/arangodb-matrix-pr/27579/

**Comment by KVS85** [comment]
- [ ] https://jenkins01.arangodb.biz/job/arangodb-matrix-pr/27580/

**Review by KVS85 — APPROVED** [review]

**Review by alexbakharew — APPROVED** [review]
LGTM

**Pull request merged**
