### PR TITLE
add test suite server_secrets

### PR DESCRIPTION
**Pull request by jsteemann**
Adds new test suite `server_secrets`.

Must be merged only after the following ArangoDB PRs have been merged:
* 3.3: https://github.com/arangodb/arangodb/pull/10979
* 3.4: https://github.com/arangodb/arangodb/pull/10982
* 3.5: https://github.com/arangodb/arangodb/pull/10981
* 3.6: https://github.com/arangodb/arangodb/pull/10980

### CODE REVIEW

**Comment by graetzer** [comment]
Do Not merge yet

**Comment by jsteemann** [comment]
@graetzer : why shouldn't this be merged? please explain so we don't need to guess.

**Comment by graetzer** [comment]
Because it’s unstable, max has a fix

**Comment by jsteemann** [comment]
http://172.16.10.101:8080/view/PR/job/arangodb-matrix-pr/8596/

**Pull request merged**
