### PR TITLE
Ubuntu/glibc-based build image

### PR DESCRIPTION
**Pull request by neunhoef**
This PR adds a new build image and build script.
It is based on Ubuntu 23.10 and thus contains glibc as C-library.
We recompile glibc with a new option to allow for statically linked
binaries. Furthermore, we put in a new version of V8, in case we want
to use it in the future.

We also add the option to package 3.11 and 3.12 with an Ubuntu based
Docker image adding a few more tools.

Finally, this also adds a so far unused build image based on Alpine
Linux 3.18, but with a modified libmusl to use glibc's string functions.
We currently do not plan to use this.

### CODE REVIEW

**Review by kvahed — COMMENTED** [review]
LGTM

**Review by kvahed — APPROVED** [review]

**Comment by KVS85** [comment]
- [ ] https://jenkins.arangodb.biz/job/arangodb-ANY-matrix/109/
- [x] https://jenkins.arangodb.biz/job/arangodb-ANY-mac-onlycompile.x86-64/164/, https://jenkins.arangodb.biz/job/arangodb-ANY-mac-onlycompile.arm64/163/
- [ ] https://jenkins.arangodb.biz/view/Performance/job/perf-simple-branch/118/

Based on this PR and https://github.com/arangodb/arangodb/tree/feature/ubuntu-static (with merged devel as of today) + https://github.com/arangodb/enterprise/tree/devel.

Additionally (for CircleCI): https://app.circleci.com/pipelines/github/arangodb/arangodb/20932

**Comment by KVS85** [comment]
https://jenkins.arangodb.biz/view/Performance/job/perf-simple-branch/118/ went into timeout due to misconfigured pipeline.

It was fixed and now restarted:
- [ ] https://jenkins.arangodb.biz/view/Performance/job/perf-simple-branch/120/

**Review by neunhoef — COMMENTED** [review]
LGTM

**Comment by KVS85** [comment]
https://github.com/arangodb/arangodb/pull/20385#issuecomment-1875608954

**Pull request merged**
