### PR TITLE
Update runPRtest.ps1

### PR DESCRIPTION
**Pull request by KVS85**

### CODE REVIEW

**Comment by fceller** [comment]
@KVS85 what is the status of this PR?

**Comment by KVS85** [comment]
Should be merged only when https://arangodb.atlassian.net/browse/COP-157 and https://arangodb.atlassian.net/browse/COP-158 are done.

**Comment by KVS85** [comment]
devel: http://jenkins.arangodb.biz:8080/job/arangodb-ANY-windows-matrix/1126/
3.6: http://jenkins.arangodb.biz:8080/job/arangodb-ANY-windows-matrix/1127/
3.5: http://jenkins.arangodb.biz:8080/job/arangodb-ANY-windows-matrix/1128/
3.4: http://jenkins.arangodb.biz:8080/job/arangodb-ANY-windows-matrix/1129/

**Comment by KVS85** [comment]
Tests OK except unrelated failures.

**Comment by KVS85** [comment]
https://github.com/arangodb/oskar/pull/177#issuecomment-538132481 - these items will be processed separately.

**Pull request merged**
